//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTextDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTextDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Resources.Strings.AppTextDisplay", typeof(AppTextDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string CategoryEntityDisplay {
            get {
                return ResourceManager.GetString("CategoryEntityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً خطاهای فرم را بررسی نموده و دوباره ارسال کنید..
        /// </summary>
        public static string ContactForm_Error {
            get {
                return ResourceManager.GetString("ContactForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ارسال گردید. به زودی پاسخ شما را خوهیم داد..
        /// </summary>
        public static string ContactForm_Success {
            get {
                return ResourceManager.GetString("ContactForm_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در بارگذاری فایل روی سرور اتفاق افتاده است..
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnTItle {
            get {
                return ResourceManager.GetString("LangEnTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string LangFaTitle {
            get {
                return ResourceManager.GetString("LangFaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت افزود شد..
        /// </summary>
        public static string ModelAddedMsg {
            get {
                return ResourceManager.GetString("ModelAddedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً خطاهای موجود را بررسی و دوباره تلاش نمایید..
        /// </summary>
        public static string ModelStateError {
            get {
                return ResourceManager.GetString("ModelStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت به روز رسانی گردید..
        /// </summary>
        public static string ModelUpdatedMsg {
            get {
                return ResourceManager.GetString("ModelUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته.
        /// </summary>
        public static string PostEntityDisplay {
            get {
                return ResourceManager.GetString("PostEntityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string PostStatusDeleted {
            get {
                return ResourceManager.GetString("PostStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نویس.
        /// </summary>
        public static string PostStatusDraft {
            get {
                return ResourceManager.GetString("PostStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آینده.
        /// </summary>
        public static string PostStatusPlanned {
            get {
                return ResourceManager.GetString("PostStatusPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر شده.
        /// </summary>
        public static string PostStatusPublished {
            get {
                return ResourceManager.GetString("PostStatusPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string StatusDisable {
            get {
                return ResourceManager.GetString("StatusDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string StatusEnable {
            get {
                return ResourceManager.GetString("StatusEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نامشخص.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت شما با موفقیت انجام شد..
        /// </summary>
        public static string Subscription_Success {
            get {
                return ResourceManager.GetString("Subscription_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند }0{ فایل برای آپلود معتبر نیست..
        /// </summary>
        public static string UploadFileExtNotValid {
            get {
                return ResourceManager.GetString("UploadFileExtNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string UserEntityDisplay {
            get {
                return ResourceManager.GetString("UserEntityDisplay", resourceCulture);
            }
        }
    }
}
