//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTextDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTextDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Resources.Strings.AppTextDisplay", typeof(AppTextDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string CategoryEntityDisplay {
            get {
                return ResourceManager.GetString("CategoryEntityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        public static string CommentStatusApproved {
            get {
                return ResourceManager.GetString("CommentStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string CommentStatusDeleted {
            get {
                return ResourceManager.GetString("CommentStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوانده شده.
        /// </summary>
        public static string CommentStatusRead {
            get {
                return ResourceManager.GetString("CommentStatusRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد شده.
        /// </summary>
        public static string CommentStatusRejected {
            get {
                return ResourceManager.GetString("CommentStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسپم.
        /// </summary>
        public static string CommentStatusSpam {
            get {
                return ResourceManager.GetString("CommentStatusSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیده شده.
        /// </summary>
        public static string CommentStatusViewed {
            get {
                return ResourceManager.GetString("CommentStatusViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تایید.
        /// </summary>
        public static string CommentStatusWaiting {
            get {
                return ResourceManager.GetString("CommentStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً خطاهای فرم را بررسی نموده و دوباره ارسال کنید..
        /// </summary>
        public static string ContactForm_Error {
            get {
                return ResourceManager.GetString("ContactForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ارسال گردید. به زودی پاسخ شما را خوهیم داد..
        /// </summary>
        public static string ContactForm_Success {
            get {
                return ResourceManager.GetString("ContactForm_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string ContactMessageStatusDeleted {
            get {
                return ResourceManager.GetString("ContactMessageStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوانده شده.
        /// </summary>
        public static string ContactMessageStatusRead {
            get {
                return ResourceManager.GetString("ContactMessageStatusRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسالی.
        /// </summary>
        public static string ContactMessageStatusSent {
            get {
                return ResourceManager.GetString("ContactMessageStatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسپم.
        /// </summary>
        public static string ContactMessageStatusSpam {
            get {
                return ResourceManager.GetString("ContactMessageStatusSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیده شده.
        /// </summary>
        public static string ContactMessageStatusViewed {
            get {
                return ResourceManager.GetString("ContactMessageStatusViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پستی.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Customer_FirstName {
            get {
                return ResourceManager.GetString("Customer_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Customer_LastName {
            get {
                return ResourceManager.GetString("Customer_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [همه].
        /// </summary>
        public static string DropDownNoSelect {
            get {
                return ResourceManager.GetString("DropDownNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده شده در نوشته.
        /// </summary>
        public static string FileStatusAttachedToPost {
            get {
                return ResourceManager.GetString("FileStatusAttachedToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string FileStatusDeleted {
            get {
                return ResourceManager.GetString("FileStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخفی.
        /// </summary>
        public static string FileStatusHidden {
            get {
                return ResourceManager.GetString("FileStatusHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده نشده.
        /// </summary>
        public static string FileStatusUnAttached {
            get {
                return ResourceManager.GetString("FileStatusUnAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در بارگذاری فایل روی سرور اتفاق افتاده است..
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string FormFieldTypeDate {
            get {
                return ResourceManager.GetString("FormFieldTypeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد با اعشار.
        /// </summary>
        public static string FormFieldTypeDecimal {
            get {
                return ResourceManager.GetString("FormFieldTypeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        public static string FormFieldTypeFile {
            get {
                return ResourceManager.GetString("FormFieldTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد صحیح.
        /// </summary>
        public static string FormFieldTypeInteger {
            get {
                return ResourceManager.GetString("FormFieldTypeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند انتخابی.
        /// </summary>
        public static string FormFieldTypeMultiSelect {
            get {
                return ResourceManager.GetString("FormFieldTypeMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخابی.
        /// </summary>
        public static string FormFieldTypeSelect {
            get {
                return ResourceManager.GetString("FormFieldTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته.
        /// </summary>
        public static string FormFieldTypeText {
            get {
                return ResourceManager.GetString("FormFieldTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادرشده.
        /// </summary>
        public static string InvoiceStatusIssued {
            get {
                return ResourceManager.GetString("InvoiceStatusIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string InvoiceStatusPaid {
            get {
                return ResourceManager.GetString("InvoiceStatusPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فاکتور.
        /// </summary>
        public static string InvoiceStatusPreOrder {
            get {
                return ResourceManager.GetString("InvoiceStatusPreOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnTItle {
            get {
                return ResourceManager.GetString("LangEnTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string LangFaTitle {
            get {
                return ResourceManager.GetString("LangFaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت افزود شد..
        /// </summary>
        public static string ModelAddedMsg {
            get {
                return ResourceManager.GetString("ModelAddedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً خطاهای موجود را بررسی و دوباره تلاش نمایید..
        /// </summary>
        public static string ModelStateError {
            get {
                return ResourceManager.GetString("ModelStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت به روز رسانی گردید..
        /// </summary>
        public static string ModelUpdatedMsg {
            get {
                return ResourceManager.GetString("ModelUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه شده.
        /// </summary>
        public static string OrderStatusAddedd {
            get {
                return ResourceManager.GetString("OrderStatusAddedd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string OrderStatusPaid {
            get {
                return ResourceManager.GetString("OrderStatusPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string PostBodyTypeHtml {
            get {
                return ResourceManager.GetString("PostBodyTypeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارک داون.
        /// </summary>
        public static string PostBodyTypeMarkdown {
            get {
                return ResourceManager.GetString("PostBodyTypeMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ساده.
        /// </summary>
        public static string PostBodyTypeText {
            get {
                return ResourceManager.GetString("PostBodyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشته.
        /// </summary>
        public static string PostEntityDisplay {
            get {
                return ResourceManager.GetString("PostEntityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string PostStatusDeleted {
            get {
                return ResourceManager.GetString("PostStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نویس.
        /// </summary>
        public static string PostStatusDraft {
            get {
                return ResourceManager.GetString("PostStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آینده.
        /// </summary>
        public static string PostStatusPlanned {
            get {
                return ResourceManager.GetString("PostStatusPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر شده.
        /// </summary>
        public static string PostStatusPublished {
            get {
                return ResourceManager.GetString("PostStatusPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول در انبار موجود نیست.
        /// </summary>
        public static string ProductStatusOurOfStock {
            get {
                return ResourceManager.GetString("ProductStatusOurOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فروش.
        /// </summary>
        public static string ProductStatusPreOrder {
            get {
                return ResourceManager.GetString("ProductStatusPreOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تولید.
        /// </summary>
        public static string ProductStatusWaitingToProduce {
            get {
                return ResourceManager.GetString("ProductStatusWaitingToProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string StatusDeleted {
            get {
                return ResourceManager.GetString("StatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string StatusDisable {
            get {
                return ResourceManager.GetString("StatusDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string StatusEnable {
            get {
                return ResourceManager.GetString("StatusEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نامشخص.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت شما با موفقیت انجام شد..
        /// </summary>
        public static string Subscription_Success {
            get {
                return ResourceManager.GetString("Subscription_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو اشتراک.
        /// </summary>
        public static string Unsubscribed {
            get {
                return ResourceManager.GetString("Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند }0{ فایل برای آپلود معتبر نیست..
        /// </summary>
        public static string UploadFileExtNotValid {
            get {
                return ResourceManager.GetString("UploadFileExtNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string UserEntityDisplay {
            get {
                return ResourceManager.GetString("UserEntityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدود.
        /// </summary>
        public static string UserStatusBlocked {
            get {
                return ResourceManager.GetString("UserStatusBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string UserStatusDeleted {
            get {
                return ResourceManager.GetString("UserStatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string UserStatusDisabled {
            get {
                return ResourceManager.GetString("UserStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string UserStatusEnabled {
            get {
                return ResourceManager.GetString("UserStatusEnabled", resourceCulture);
            }
        }
    }
}
