//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Resources.Strings.ModelText", typeof(ModelText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر شما.
        /// </summary>
        public static string Comment_Body {
            get {
                return ResourceManager.GetString("Comment_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل شما.
        /// </summary>
        public static string Comment_Email {
            get {
                return ResourceManager.GetString("Comment_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Comment_Title {
            get {
                return ResourceManager.GetString("Comment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب سایت شما.
        /// </summary>
        public static string Comment_Website {
            get {
                return ResourceManager.GetString("Comment_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string Contact_Message {
            get {
                return ResourceManager.GetString("Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شما.
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string Contact_Phone {
            get {
                return ResourceManager.GetString("Contact_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر کاور.
        /// </summary>
        public static string CoverPhoto {
            get {
                return ResourceManager.GetString("CoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Customer_Email {
            get {
                return ResourceManager.GetString("Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language_Select {
            get {
                return ResourceManager.GetString("Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه‌ی عبور.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به‌خاطر سپاری کلمه‌ی عبور؟.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ترتیب نمایش.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان جایگزین.
        /// </summary>
        public static string PostAltTitle {
            get {
                return ResourceManager.GetString("PostAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string PostBody {
            get {
                return ResourceManager.GetString("PostBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نظرات.
        /// </summary>
        public static string PostCommenting {
            get {
                return ResourceManager.GetString("PostCommenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز مطلب.
        /// </summary>
        public static string PostPassword {
            get {
                return ResourceManager.GetString("PostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتشار.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مدل محصول.
        /// </summary>
        public static string Select_ProductModel {
            get {
                return ResourceManager.GetString("Select_ProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامک.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Subscriber_Email {
            get {
                return ResourceManager.GetString("Subscriber_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شما.
        /// </summary>
        public static string Subscriber_Name {
            get {
                return ResourceManager.GetString("Subscriber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
