//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Resources.Strings.ModelError", typeof(ModelError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً آدرس ایمیل خود را وارد نمایید..
        /// </summary>
        public static string Contact_Email_Required {
            get {
                return ResourceManager.GetString("Contact_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً پیام خود را وارد نمایید..
        /// </summary>
        public static string Contact_Message_Required {
            get {
                return ResourceManager.GetString("Contact_Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام خود را وارد نمایید.
        /// </summary>
        public static string Contact_Name_Required {
            get {
                return ResourceManager.GetString("Contact_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شماره تماس خود را وارد نمایید..
        /// </summary>
        public static string Contact_Phone_Required {
            get {
                return ResourceManager.GetString("Contact_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً شماره تماس را به درستی وارد نمایید..
        /// </summary>
        public static string Contact_Phone_Wrong {
            get {
                return ResourceManager.GetString("Contact_Phone_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت آدرس ایمیل اشتباه است.
        /// </summary>
        public static string Email_Wrong {
            get {
                return ResourceManager.GetString("Email_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً خطاهای فرم را بررسی کرده و دوباره ارسال نمایید..
        /// </summary>
        public static string Form_Input_Error {
            get {
                return ResourceManager.GetString("Form_Input_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکترها بیشتر از حد مجاز است..
        /// </summary>
        public static string MaxLen {
            get {
                return ResourceManager.GetString("MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً آدرس ایمیل تان را وارد کنید..
        /// </summary>
        public static string Subscriber_Email_Required {
            get {
                return ResourceManager.GetString("Subscriber_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده اشتباه است..
        /// </summary>
        public static string Wrong_Number {
            get {
                return ResourceManager.GetString("Wrong_Number", resourceCulture);
            }
        }
    }
}
